// Post-`cap add android` patcher. Idempotent — safe to run repeatedly.
// 1) Injects the AdMob APPLICATION_ID meta-data (required: without it the app crashes
//    on launch when AdMob initializes) + a strings.xml entry to hold the real ID.
// 2) Wires CLI release signing via a separate signing.gradle (so `npm run build:aab`
//    produces a signed .aab when android/key.properties exists). No fragile edits to
//    the android{} block — signing.gradle reopens android{} and is conditional.
// Run from wrapper/ after the android/ project exists:  npm run patch
const fs = require('fs');
const path = require('path');
const appDir = path.resolve(__dirname, 'android', 'app');
const A = path.join(appDir, 'src', 'main');
const manifestPath = path.join(A, 'AndroidManifest.xml');
const stringsPath = path.join(A, 'res', 'values', 'strings.xml');
const gradlePath = path.join(appDir, 'build.gradle');
const signingGradlePath = path.join(appDir, 'signing.gradle');

if (!fs.existsSync(manifestPath)) {
  console.error('✗ android/ project not found. Run "npm run add:android" first.');
  process.exit(1);
}

// 1) strings.xml — add admob_app_id placeholder if missing
let strings = fs.readFileSync(stringsPath, 'utf8');
if (!strings.includes('admob_app_id')) {
  strings = strings.replace('</resources>',
    '    <string name="admob_app_id">ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXXXXX</string>\n</resources>');
  fs.writeFileSync(stringsPath, strings);
  console.log('✓ Added admob_app_id to strings.xml  (replace with your REAL AdMob APP ID)');
} else { console.log('• strings.xml already has admob_app_id'); }

// 2) AndroidManifest.xml — add AdMob meta-data inside <application> if missing
let manifest = fs.readFileSync(manifestPath, 'utf8');
if (!manifest.includes('com.google.android.gms.ads.APPLICATION_ID')) {
  manifest = manifest.replace('</application>',
    '        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="@string/admob_app_id"/>\n    </application>');
  fs.writeFileSync(manifestPath, manifest);
  console.log('✓ Added AdMob APPLICATION_ID meta-data to AndroidManifest.xml');
} else { console.log('• AndroidManifest already has the AdMob meta-data'); }

// 3) Release signing — drop signing.gradle and apply it from build.gradle (idempotent)
const signingGradle = `// Auto-generated by patch-android.js. Conditional release signing.
// Put your values in android/key.properties (copy from wrapper/key.properties.example).
// If key.properties is absent, the release build is simply unsigned (use the Studio wizard instead).
def keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    def keystoreProperties = new Properties()
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    android {
        signingConfigs {
            release {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
}
`;
fs.writeFileSync(signingGradlePath, signingGradle);
let gradle = fs.readFileSync(gradlePath, 'utf8');
if (!gradle.includes("apply from: 'signing.gradle'") && !gradle.includes('apply from: "signing.gradle"')) {
  gradle = gradle.trimEnd() + "\n\napply from: 'signing.gradle'\n";
  fs.writeFileSync(gradlePath, gradle);
  console.log("✓ Wrote signing.gradle and added apply line to app/build.gradle");
} else { console.log('• build.gradle already applies signing.gradle'); }

console.log('\nNext:');
console.log('  1) Put your REAL AdMob APP ID in android/app/src/main/res/values/strings.xml (admob_app_id).');
console.log('  2) Signing: copy wrapper/key.properties.example -> android/key.properties and fill it in,');
console.log('     then:  npm run build:aab   ->   android/app/build/outputs/bundle/release/app-release.aab');
console.log('     (Or skip key.properties and use Android Studio: Build > Generate Signed Bundle.)');
console.log('  3) (Optional analytics) drop google-services.json into android/app/ + enable the');
console.log('     google-services Gradle plugin (RELEASE_CHECKLIST.md section F). Without it, analytics');
console.log('     no-ops and the app still builds & runs.\n');
