// Post-`cap add android` patcher. Idempotent — safe to run repeatedly.
// 1) Injects the AdMob APPLICATION_ID meta-data (required: without it the app crashes
//    on launch when AdMob initializes) + a strings.xml entry to hold the real ID.
// 2) Wires CLI release signing via a separate signing.gradle (so `npm run build:aab`
//    produces a signed .aab when android/key.properties exists). No fragile edits to
//    the android{} block — signing.gradle reopens android{} and is conditional.
// Run from wrapper/ after the android/ project exists:  npm run patch
const fs = require('fs');
const path = require('path');
const appDir = path.resolve(__dirname, 'android', 'app');
const A = path.join(appDir, 'src', 'main');
const manifestPath = path.join(A, 'AndroidManifest.xml');
const stringsPath = path.join(A, 'res', 'values', 'strings.xml');
const gradlePath = path.join(appDir, 'build.gradle');
const signingGradlePath = path.join(appDir, 'signing.gradle');

if (!fs.existsSync(manifestPath)) {
  console.error('✗ android/ project not found. Run "npm run add:android" first.');
  process.exit(1);
}

// 1) strings.xml — add admob_app_id placeholder if missing
let strings = fs.readFileSync(stringsPath, 'utf8');
if (!strings.includes('admob_app_id')) {
  strings = strings.replace('</resources>',
    '    <string name="admob_app_id">ca-app-pub-7340441888702917~7465648358</string>\n</resources>');
  fs.writeFileSync(stringsPath, strings);
  console.log('✓ Added admob_app_id to strings.xml  (replace with your REAL AdMob APP ID)');
} else { console.log('• strings.xml already has admob_app_id'); }

// 2) AndroidManifest.xml — add AdMob meta-data inside <application> if missing
let manifest = fs.readFileSync(manifestPath, 'utf8'); const beforeM = manifest;
if (!manifest.includes('com.google.android.gms.ads.APPLICATION_ID')) {
  manifest = manifest.replace('</application>',
    '        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="@string/admob_app_id"/>\n    </application>');
}
// Families/child-directed: strip the AD_ID permission AdMob auto-adds (so we can declare "no advertising ID")
if (!manifest.includes('xmlns:tools=')) {
  manifest = manifest.replace('xmlns:android="http://schemas.android.com/apk/res/android"',
    'xmlns:android="http://schemas.android.com/apk/res/android"\n    xmlns:tools="http://schemas.android.com/tools"');
}
if (!manifest.includes('permission.AD_ID')) {
  manifest = manifest.replace('</manifest>',
    '    <uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove" />\n</manifest>');
}
if (manifest !== beforeM) { fs.writeFileSync(manifestPath, manifest); console.log('✓ Patched AndroidManifest (AdMob meta + AD_ID removal)'); }
else { console.log('• AndroidManifest already patched'); }

// 3) Release signing — drop signing.gradle and apply it from build.gradle (idempotent)
const signingGradle = `// Auto-generated by patch-android.js. Conditional release signing.
// Put your values in android/key.properties (copy from wrapper/key.properties.example).
// If key.properties is absent, the release build is simply unsigned (use the Studio wizard instead).
def keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    def keystoreProperties = new Properties()
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    android {
        signingConfigs {
            release {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
}
`;
fs.writeFileSync(signingGradlePath, signingGradle);
let gradle = fs.readFileSync(gradlePath, 'utf8');
if (!gradle.includes("apply from: 'signing.gradle'") && !gradle.includes('apply from: "signing.gradle"')) {
  gradle = gradle.trimEnd() + "\n\napply from: 'signing.gradle'\n";
  fs.writeFileSync(gradlePath, gradle);
  console.log("✓ Wrote signing.gradle and added apply line to app/build.gradle");
} else { console.log('• build.gradle already applies signing.gradle'); }

// 4) Ensure compile/target SDK >= 35 (Google Play requires API 35 for new apps)
const varPath = path.join(__dirname, 'android', 'variables.gradle');
if (fs.existsSync(varPath)) {
  let v = fs.readFileSync(varPath, 'utf8'); const before = v;
  v = v.replace(/compileSdkVersion\s*=\s*3[0-4]\b/, 'compileSdkVersion = 35')
       .replace(/targetSdkVersion\s*=\s*3[0-4]\b/, 'targetSdkVersion = 35');
  if (v !== before) { fs.writeFileSync(varPath, v); console.log('✓ Bumped compile/target SDK to 35 (Play requirement)'); }
  else { console.log('• variables.gradle already at SDK 35+'); }
}

// 5) Android 15 edge-to-edge opt-out (else the bottom nav draws under the system nav bar)
const stylesPath = path.join(A, 'res', 'values', 'styles.xml');
if (fs.existsSync(stylesPath)) {
  let st = fs.readFileSync(stylesPath, 'utf8');
  if (!st.includes('windowOptOutEdgeToEdgeEnforcement')) {
    st = st.replace('<item name="android:background">@null</item>',
      '<item name="android:background">@null</item>\n        <item name="android:windowOptOutEdgeToEdgeEnforcement">true</item>');
    fs.writeFileSync(stylesPath, st);
    console.log('✓ Opted out of Android 15 edge-to-edge (styles.xml)');
  } else { console.log('• styles.xml already opts out of edge-to-edge'); }
}

console.log('\nNext:');
console.log('  1) Put your REAL AdMob APP ID in android/app/src/main/res/values/strings.xml (admob_app_id).');
console.log('  2) Signing: copy wrapper/key.properties.example -> android/key.properties and fill it in,');
console.log('     then:  npm run build:aab   ->   android/app/build/outputs/bundle/release/app-release.aab');
console.log('     (Or skip key.properties and use Android Studio: Build > Generate Signed Bundle.)');
console.log('  3) (Optional analytics) drop google-services.json into android/app/ + enable the');
console.log('     google-services Gradle plugin (RELEASE_CHECKLIST.md section F). Without it, analytics');
console.log('     no-ops and the app still builds & runs.\n');
